# Generated by Django 5.2.3 on 2025-06-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='concept',
            field=models.CharField(default='未分類', max_length=100),
        ),
    ]
