# Generated by Django 5.2.3 on 2025-07-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
