# Generated by Django 5.2.3 on 2025-07-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_question_question_type_alter_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', '選擇題'), ('tf', '是非題')], default='mcq', max_length=20),
        ),
    ]
