# Generated by Django 5.2.3 on 2025-09-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_submission_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='created_at',
        ),
    ]
