# Generated by Django 5.2.3 on 2025-10-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_submission_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='student_answer',
            field=models.CharField(max_length=200),
        ),
    ]
